jobs:
  - job: TestStuff
    strategy: 
      matrix:
        macos-12:
          Pool: Azure Pipelines
          VmImage: macOS-12

        macos-11:
          Pool: Azure Pipelines
          VmImage: macOS-11

        macos-1015:
          Pool: Azure Pipelines
          VmImage: macOS-10.15

    pool:
      name: $(Pool)
      vmImage: $(VmImage)

    steps:    
      - bash: |
          which bicep

