jobs:
  - job: TryMacOSDocker
    strategy: 
      matrix:
        macos12:
          Pool: Azure Pipelines
          VmImage: macOS-12

        macos11: 
          Pool: Azure Pipelines
          VmImage: macOS-11

    pool:
      name: $(Pool)
      vmImage: $(VmImage)

    steps:    
      - pwsh: Write-Host "Will we succeed?"      

      - task: DockerInstaller@0.214.0
        displayName: Docker Installer
        condition: and(succeeded(), contains(variables['VmImage'], 'macOS'))
        inputs:
          dockerVersion: 17.09.0-ce
          releaseType: stable

      - pwsh: Write-Host "Did we succeed?"
