# trigger: 
#   branches:
#     include:
#       - main

pr:
  branches:
    include:
      - main

jobs: 
  - job: setupazd
    variables:
      PoolName: azsdk-pool
      Demand: ImageOverride -equals $(ImageName)
      ImageName: ubuntu-24.04
    pool:
      name: $(PoolName)
      demands: $(Demand)

    steps: 
      - pwsh: Write-Host "Hello World"
        displayName: Hello World

      - pwsh: nuget
        displayName: nuget
