jobs:
  - job: TryWsl

    strategy:
      matrix: 
        m1: {}
        m2: {}
        m3: {}
        m4: {}
        m5: {}
      maxParallel: 3

    pool: azsdk-pool-mms-win-2022-general

    steps:
      - pwsh: |
          function assertGoodExit { 
            if ($LASTEXITCODE) { 
              Write-Host "ERROR: Last exit code: $LASTEXITCODE"
              exit $LASTEXITCODE
            }
          }

          # Write-Host "wsl.exe wsl --set-default-version 2"
          # wsl.exe wsl --set-default-version 2
          # assertGoodExit

          # Write-Host "wsl.exe --update"
          # wsl.exe --update
          # assertGoodExit

          Write-Host "sc query type=service"
          sc query type=service

          Write-Host "Get-WindowsOptionalFeature -Online"
          Get-WindowsOptionalFeature -Online
          
          # Write-Host "Get-Service"
          # Get-Service 
          
          Write-Host "Get-Service WslService"
          Get-Service WslService

          Write-Host "wsl --status" 
          wsl --status 
          assertGoodExit

          Write-Host "wsl --list --all --online" 
          wsl --list --all --online
          assertGoodExit

          write-host "WSL install of ubuntu."
          Write-Host "wsl --install -d Ubuntu-20.04 --no-launch"
          wsl --install -d Ubuntu-20.04 --no-launch 
          assertGoodExit

          write-host "Launch WSL."
          wsl
          [console]::OutputEncoding = New-Object System.Text.UnicodeEncoding
          $wsl = wsl -l -v | out-string
          assertGoodExit

          write-host $wsl
          while ($wsl -notmatch 'Ubuntu-20.04.*running') {
            start-sleep -seconds 1
            $wsl = wsl -l -v | out-string
            assertGoodExit
            write-host $wsl

            Write-Host "wsl --status"
            wsl --status
            assertGoodExit
          }
          write-host "Ubuntu installed."
        displayName: Install WSL

      - pwsh: | 
          wsl sudo apt-get update
          wsl sudo apt-get -y install squid
        displayName: Install squid
