jobs: 
  - job: Verify_LinuxPackages

    strategy:
      matrix:
        LinuxAMD64: 
          Pool: azsdk-pool-mms-ubuntu-2004-general
          OSVmImage:  MMSUbuntu20.04
          Architecture: amd64
        LinuxARM64:
          Pool: azsdk-pool-mms-ubuntu-2004-arm
          OSVmImage: MMSUbuntu20.04ARM64
          Architecture: arm64
        
    pool:
      name: $(Pool)
      vmImage: $(OSVmImage)

    steps: 
      - checkout: self

      - bash: |
          # Install PowerShell
          # https://learn.microsoft.com/en-us/powershell/scripting/install/install-other-linux?view=powershell-7.3#binary-archives
          sudo apt update
          sudo apt install -y curl
          temp_dir=$(mktemp -d /tmp/tool-preinstall-XXXXXXXX)
          curl -L -o "$temp_dir/powershell.tar.gz" https://github.com/PowerShell/PowerShell/releases/download/v7.3.6/powershell-7.3.6-linux-arm64.tar.gz
          sudo mkdir -p /opt/microsoft/powershell/7
          sudo tar zxf "$temp_dir/powershell.tar.gz" -C /opt/microsoft/powershell/7
          sudo chmod +x /opt/microsoft/powershell/7/pwsh
          sudo ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh

          echo "PowerShell install complete:"
          pwsh --version
        condition: eq('arm64', variables['Architecture'])
        displayName: Install pwsh on arm64 agent

      - task: PowerShell@2
        displayName: Verify Linux Packages
        inputs: 
          pwsh: true
          filePath: Write-HelloWorld.ps1
