# trigger: 
#   branches:
#     include:
#       - main


jobs: 
  - job: setupazd
    strategy: 
      matrix:
        Windows:
          vmImage: windows-latest
        Linux:
          vmImage: ubuntu-latest
        Mac:
          vmImage: macos-latest

    pool:
      vmImage: $(vmImage)

    steps: 
      - pwsh: |
          Invoke-RestMethod 'https://aka.ms/install-azd.ps1' -OutFile install-azd.ps1
          ./install-azd.ps1 -BaseUrl 'https://azdrelease.azureedge.net/azd/standalone'
          Remove-Item ./install-azd.ps1
        displayName: Install azd (mitigation)

      - pwsh: azd version
