stages: 
  - stage: PartialSuccess
    jobs:
      - job: Succeed
        steps: 
          - pwsh: Write-Host "Success!"
      - job: Fail
        steps: 
          - pwsh: Write-Error "Failed!"; exit 1
  - stage: DependsOn
    dependsOn: PartialSuccess
    condition: eq(dependencies.PartialSuccess.Succeeded.result, 'Succeeded')
    jobs: 
      - job: RunMe
        steps: 
          - pwsh: Write-Host "RunMe!"
