# trigger: 
#   branches:
#     include:
#       - main

# pr:
#   branches:
#     include:
#       - main

jobs:
  - job: linux
    pool:
      name: azsdk-pool
      demands: ImageOverride -equals ubuntu-24.04

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 20.x

    - pwsh: |
        npm i -g npm tfx-cli
      displayName: Install tfx-cli
