jobs:
  - job: TryWsl
    pool: azsdk-pool-mms-win-2022-general

    steps:
      - pwsh: |
          function assertGoodExit { 
            if ($LASTEXITCODE) { 
              Write-Host "ERROR: Last exit code: $LASTEXITCODE"
              exit $LASTEXITCODE
            }
          }

          Write-Host "wsl --status" 
          wsl --status 

          Write-Host "wsl --list --all --online" 
          wsl --list --all --online

          exit 1

          write-host "WSL install of ubuntu."
          Write-Host "wsl --install -d Ubuntu-20.04"
          wsl --install -d Ubuntu-20.04 
          assertGoodExit

          write-host "Launch WSL."
          wsl
          [console]::OutputEncoding = New-Object System.Text.UnicodeEncoding
          $wsl = wsl -l -v | out-string
          assertGoodExit

          write-host $wsl
          while ($wsl -notmatch 'Ubuntu-20.04.*running') {
            start-sleep -seconds 1
            $wsl = wsl -l -v | out-string
            assertGoodExit
            write-host $wsl

            Write-Host "wsl --status"
            wsl --status
            assertGoodExit
          }
          write-host "Ubuntu installed."
        displayName: Install WSL

      - pwsh: | 
          wsl sudo apt-get update
          wsl sudo apt-get -y install squid
        displayName: Install squid
