jobs:
  - job: TryMacOSDocker
    strategy: 
      matrix:
        macos12:
          Pool: Azure Pipelines
          VmImage: windows-2019

    pool:
      name: $(Pool)
      vmImage: $(VmImage)

    steps:    
      - pwsh: windres 
        displayName: Run windres

