jobs:
  - job: TestStuff
    strategy: 
      matrix:
        ubuntu-2204:
          Pool: Azure Pipelines
          VmImage: ubuntu-22.04

    pool:
      name: $(Pool)
      vmImage: $(VmImage)

    steps:    
      - bash: apt update && apt install gcovr lcov
        displayName: apt install
