jobs:
  - job: TryWsl
    strategy: 
      matrix:
        PipelinesHostedPool2022:
          Pool: Azure Pipelines
          VmImage: windows-2022

        PipelinesHostedPool2019:
          Pool: Azure Pipelines
          VmImage: windows-2019

        SelfHostedPool2022: 
          Pool: azsdk-pool-mms-win-2022-general
          VmImage: __UNUSED__

        SelfHostedPool2019: 
          Pool: azsdk-pool-mms-win-2019-general
          VmImage: __UNUSED__

    pool:
      name: $(Pool)
      vmImage: $(VmImage)

    steps:
      # - pwsh: bash.exe -c "pwd; ls; cat /etc/lsb-release; apt update; lsb_release -a"
      #   displayName: bash.exe -c "lsb_release -a"

      - pwsh: |
          Write-Host "wsl --status" 
          wsl --status 

          Write-Host "wsl --list --online" 
          wsl --list --online

          write-host "WSL install of ubuntu."
          Write-Host "wsl --install -d Ubuntu-20.04"
          wsl --install -d Ubuntu-20.04

          Write-Host "wsl --list --all --verbose | out-string"
          $wsl = wsl --list --all --verbose | out-string
          write-host $wsl

          while ($wsl -notmatch 'Ubuntu-20.04.*running') {
            start-sleep -seconds 1
            Write-Host "wsl --list --all --verbose | out-string"
            $wsl = wsl --list --all --verbose | out-string
            write-host $wsl

            Write-Host "wsl --status"
            wsl --status
          }
          write-host "Ubuntu installed."
        displayName: Install WSL

