jobs:
  - job: TestStuff
    strategy: 
      matrix:
        ubuntu-2204-1es:
          Pool: Azure Pipelines
          VmImage: ubuntu-22.04
        ubuntu-2204:
          Pool: azsdk-pool-mms-ubuntu-2204-general
          VmImage: MMSUbuntu22.04

    pool:
      name: $(Pool)
      vmImage: $(VmImage)

    steps:    
      - bash: sudo apt update && sudo apt install gcovr lcov
        displayName: apt install
