jobs:
  - job: TestStuff
    strategy: 
      matrix:
        ubuntu-2204-azpipelines:
          Pool: Azure Pipelines
          VmImage: ubuntu-22.04
        ubuntu-2204-1es:
          Pool: azsdk-pool-mms-ubuntu-2204-general
          VmImage: MMSUbuntu22.04

    pool:
      name: $(Pool)
      vmImage: $(VmImage)

    steps:
      - bash: |
          ls -l /etc/apt/sources.list.d/
          
          echo "/etc/apt/sources.list.d/microsoft-prod.list"
          cat /etc/apt/sources.list.d/microsoft-prod.list
          echo ""
          echo "/etc/apt/sources.list.d/azure.list"
          cat /etc/apt/sources.list.d/azure.list

          sudo rm /etc/apt/sources.list.d/microsoft-prod.list /etc/apt/sources.list.d/azure.list
          ls -l /etc/apt/sources.list.d/
        displayName: Workaround, remove Microsoft apt sources

      - bash: sudo apt update && sudo apt install gcovr lcov
        displayName: apt install
