jobs:
  - job: predefineds
    strategy:
      matrix:
        Win:
          vmImage: windows-2019
        Linux:
          vmImage: ubuntu-20.04
    pool:
      vmImage: $(vmImage)

    variables:
      TEST_RUNTIME_SETTINGS: ONE

    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python 3'
        inputs:
          versionSpec: '3'

      - task: PowerShell@2
        displayName: 'Launch background process'
        inputs:
          pwsh: true
          filePath: Start-BackgroundService.ps1

      - pwsh: |
          Start-Sleep -Seconds 5
        displayName: Sleep for 5 seconds

      - pwsh: Get-Process | Select-Object -Property Id,Name,CommandLine
        displayName: List all processes

      - script: ps -x | grep python
        condition: contains(variables['Agent.OS'], 'ubuntu')

      - pwsh: |
          Stop-Process -Id $(ServerProcessId)
        displayName: Stop long running service

      - pwsh: |
          Write-Host "WebSocketServer.log"
          Get-Content WebSocketServer.log

          Write-Host "WebSocketServer.err.log"
          Get-Content WebSocketServer.err.log
        condition: always()
        displayName: Show logs
