jobs:
  - job: TryWsl
    strategy: 
      matrix:
        PipelinesHostedPool2022:
          Pool: Azure Pipelines
          VmImage: windows-2022

        SelfHostedPool2022: 
          Pool: azsdk-pool-mms-win-2022-general
          VmImage: __UNUSED__
          Demands: ImageVersionOverride -equals 

    pool:
      name: $(Pool)
      vmImage: $(VmImage)

    steps:
      - pwsh: |
          Write-Host "wsl --update --web-download"
          wsl --update --web-download | Out-String
          
          Write-Host "wsl --status" 
          wsl --status 

          Write-Host "wsl --list --online" 
          wsl --list --online

          write-host "WSL install of ubuntu."
          Write-Host "wsl --install -d Ubuntu-20.04 --web-download"
          wsl --install -d Ubuntu-20.04 --web-download

          Write-Host "wsl --list --all --verbose | out-string"
          $wsl = wsl --list --all --verbose | out-string
          write-host $wsl

          $checkCount = 0
          while ($wsl -notmatch 'Ubuntu-20.04.*running') {
            $checkCount++
            if ($checkCount -gt 30) { 
              Write-Host "Failed to detect start in time"
              exit 1
            }
            start-sleep -seconds 1
            Write-Host "wsl --list --all --verbose | out-string"
            $wsl = wsl --list --all --verbose | out-string
            write-host $wsl
          }
          write-host "Ubuntu installed."
        displayName: Install WSL

