# trigger: 
#   branches:
#     include:
#       - main

pr:
  branches:
    include:
      - main

jobs: 
  - job: setupazd
    variables:
      PoolName: azsdk-pool
      Demand: ImageOverride -equals $(ImageName)
      ImageName: ubuntu-24.04
    pool:
      name: $(PoolName)
      demands: $(Demand)

    steps: 
      - pwsh: Write-Host "Hello World"
        displayName: Hello World

      - pwsh: |
          Write-Host "Download nuget..."
          Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe
          
          Write-Host "Run nuget..."
          dotnet run ./nuget.exe
        displayName: nuget
