# trigger: 
#   branches:
#     include:
#       - main

# pr:
#   branches:
#     include:
#       - main

jobs:
  - job: linux
    pool:
      name: azsdk-pool
      demands: ImageOverride -equals ubuntu-20.24

    steps:
    - pwsh: |
        npm i -g npm tfx-cli
      displayName: Install tfx-cli
