jobs:
  - job: TestStuff
    strategy: 
      matrix:
        win2019:
          Pool: Azure Pipelines
          VmImage: windows-2019

        win2022:
          Pool: Azure Pipelines
          VmImage: windows-2022

    pool:
      name: $(Pool)
      vmImage: $(VmImage)

    steps:    
      - pwsh: windres 
        displayName: Run windres

