jobs:
  - job: TestStuff
    strategy: 
      matrix:
        ubuntu-2004:
          Pool: Azure Pipelines
          VmImage: ubuntu-20.04

    pool:
      name: $(Pool)
      vmImage: $(VmImage)

    steps:    
      - bash: git clone https://github.com/jordansissel/fpm.git
      
      - bash: docker build . -t fpm
        workingDirectory: fpm
      
      - bash: docker run fpm --help 
