# trigger: 
#   branches:
#     include:
#       - main

# pr:
#   branches:
#     include:
#       - main

jobs:
  - template: /test-network-go-dev.yml
    parameters:
      ImageOverride: windows-2022
