# trigger: 
#   branches:
#     include:
#       - main


jobs: 
  - job: setupazd
    strategy: 
      matrix:
        Windows:
          vmImage: windows-latest
        Linux:
          vmImage: ubuntu-latest
        Mac:
          vmImage: macos-latest

    pool:
      vmImage: $(vmImage)

    steps: 
      - pwsh: Write-Host "$(Build.Repository.Name)"
        displayName: Variables
