jobs:
  - job: TryWsl

    strategy:
      matrix: 
        m1: {}
        m2: {}
        m3: {}
        m4: {}
        m5: {}
      maxParallel: 3

    pool: azsdk-pool-mms-win-2022-general

    steps:
      - pwsh: |
          write-host "WSL install of ubuntu."
          wsl --install -d Ubuntu-20.04

          write-host "Launch WSL."
          [console]::OutputEncoding = New-Object System.Text.UnicodeEncoding
          $wsl = wsl -l -v | out-string

          write-host $wsl
          while ($wsl -notmatch 'Ubuntu-20.04.*running') {
            start-sleep -seconds 1
            $wsl = wsl -l -v | out-string
            write-host $wsl
          }
          write-host "Ubuntu installed."
        displayName: Install WSL

      - pwsh: | 
          wsl sudo apt-get update
          wsl sudo apt-get -y install squid
        displayName: Install squid
