# trigger: 
#   branches:
#     include:
#       - main


jobs: 
  - job: setupazd
    strategy: 
      matrix:
        Windows:
          vmImage: windows-latest
        Linux:
          vmImage: ubuntu-latest
        Mac:
          vmImage: macos-latest

    pool:
      vmImage: $(vmImage)

    steps: 
      - pwsh: Invoke-RestMethod 'https://aka.ms/install-azd.ps1' | Invoke-Expression
        displayName: Install azd (mitigation)

      - pwsh: azd version
