# trigger: 
#   branches:
#     include:
#       - main


jobs: 
  - job: setupazd
    variables:
      PoolName: azsdk-pool
      Demand: ImageOverride -equals ubuntu-24.04
    pool:
      name: $(PoolName)
      demands: $(Demand)

    steps: 
      - pwsh: Write-Host "Hello World"
        displayName: Hello World
