# trigger: 
#   branches:
#     include:
#       - main

parameters:
  - name: release_artifact_1
    displayName: Artifact1
    default: true
  - name: release_artifact_2
    displayName: Artifact2
    default: true
  - name: release_artifact_3
    displayName: Artifact3
    default: true

pr:
  branches:
    include:
      - main

jobs: 
  - job: setupazd
    pool:
      name: $(PoolName)

    steps: 
      - template: /release-artifacts.yml
        parameters:
          Artifacts:
            - name: artifact_1
              releaseInBatch: ${{ parameters.release_artifact_1 }}
            - name: artifact_2
              releaseInBatch: ${{ parameters.release_artifact_2 }}
            - name: artifact_3
              releaseInBatch: ${{ parameters.release_artifact_3 }}
