# trigger: 
#   branches:
#     include:
#       - main

# pr:
#   branches:
#     include:
#       - main

jobs:
  - job: windows
    pool:
      name: azsdk-pool
      demands: ImageOverride -equals windows-2025

    steps:
      - pwsh: winget search azd
        displayName: Run winget
