# trigger: 
#   branches:
#     include:
#       - main

# pr:
#   branches:
#     include:
#       - main

jobs:
  - job: disk_space
    pool:
      name: azsdk-pool
      demands: ImageOverride -equals ubuntu-22.04

    steps:
      - script: |
          lsblk -o NAME,SIZE
          df -h
        displayName: Disk capacity
