# trigger: 
#   branches:
#     include:
#       - main


stages:
  - stage: DynamicMatrix
    jobs: 
      - job: CreateDynamicMatrix
        steps: 
          - pwsh: |
              Write-Host '##vso[task.setvariable variable=Matrix;isOutput=true]{"RunMe": { "name": "runme" }, "SkipMe": { "name": "thing-terraform-thing" }}'


      - job: ConsumeDynamicMatrix
        dependsOn: CreateDynamicMatrix
        condition: not(contains(variables['name'], 'terraform'))

        strategy:
          matrix: $[ dependencies.CreateDynamicMatrix.outputs['Matrix'] ]
        
        steps: 
          - pwsh: Write-Host "hello world! $(name)"

  - stage: StaticMatrix
    jobs: 
      - job: ConsumeStaticMatrix
        condition: not(contains(variables['name'], 'terraform'))

        strategy: 
          matrix: 
            RunMe: 
              name: runme
            SkipMe:
              name: thing-terraform-thing
        steps: 
          - pwsh: Write-Host "hello world! $(name)"
          - pwsh: Write-Host "No terraform here..."
            condition: not(contains(variables['name'], 'terraform'))

