# trigger: 
#   branches:
#     include:
#       - main


jobs: 
  - job: Test-setupAzd
    steps: 
      - pwsh: Invoke-RestMethod 'https://aka.ms/install-azd.ps1' | Invoke-Expression
        displayName: Install azd (mitigation)

      - pwsh: azd version
