stages: 
  - stage: PartialSuccess
    jobs:
      - job: Succeed
        steps: 
          - pwsh: Write-Host "Success!"
      - job: Fail
        steps: 
          - pwsh: Write-Error "Failed!"; exit 1
  - stage: DependsOn
    dependsOn: PartialSuccess

    jobs: 
      - job: RunMe
        steps: 
          - pwsh: Write-Host "RunMe!"
