jobs:
  - job: publish
    pool:
      # vmImage: ubuntu-latest
      vmImage: windows-2019
    variables:
      TEST_RUNTIME_SETTINGS: ONE
      SetAtVariable: YEP

    steps:
      - pwsh: |
          New-Item -ItemType Directory -Path publishdir
          "Hello world" | Set-Content  publishdir/test.txt
        displayName: Write to test.txt

      - task: UniversalPackages@0
        displayName: Universal Publish
        inputs:
          command: publish
          publishDirectory: publish
          vstsFeedPublish: 'playground/djurek-test-artifact-feed'
          vstsFeedPackagePublish: 'test-universal-package'
          versionOption: minor
          packagePublishDescription: A simple test of publishing funcitonality

  - job: consume
    pool:
      # vmImage: ubuntu-latest
      vmImage: windows-2019
    variables:
      TEST_RUNTIME_SETTINGS: ONE
      SetAtVariable: YEP
    
    steps:
      - task: UniversalPackages@0
        displayName: 'Universal download'
        inputs:
          command: download
          vstsFeed: 'playground/djurek-test-artifact-feed'
          vstsFeedPackage: 'test-universal-package'
          downloadDirectory: '$(Build.SourcesDirectory)\someFolder'

      - pwsh: |
          Get-ChildItem $(Build.SourcesDirectory)\someFolder
          Get-ChildItem $(Build.SourcesDirectory)\someFolder | Get-Content
        displayName: Show file content
