parameters:
  ForkUrl: not-specified
  RepoName: not-specified
  IncrementCommand: not-specified
  BranchName: version-increment-build-$(Build.BuildId)
  PackageName: package-not-specified

jobs:
  - job: CloneToPr
    strategy:
      matrix:
        Windows:
          OSVmImage: windows-2019
        Linux:
          OSVmImage: ubuntu-16.04
        OSX:
          OSVmImage: macOS-10.13

    pool:
      vmImage: $(OSVmImage)

    steps:
      - bash: |
          cd ..
          echo echo \$GITHUB_PAT > git-pat.sh
          chmod +x git-pat.sh
        displayName: Create token script

      - bash: |
          git remote add fork ${{ parameters.ForkUrl }}
        displayName: Add GitHub fork remote

      - bash: |
          git checkout -b ${{ parameters.BranchName }}

      - bash: |
          ${{ parameters.IncrementCommand }}
        displayName: Increment Version

      - bash: |
          git config --global user.name "Azure SDK Bot"
          git config --global user.email "azuresdk@microsoft.com"
          git add .
          git commit -m "Increment package version after release ${{ parameters.PackageName }}"
        displayName: Commit

      - bash: |
          git push -u fork ${{ parameters.BranchName }}
        displayName: Push
        env:
          GITHUB_PAT: $(github-pat)
          GIT_ASKPASS: ../git-pat.sh

      # TODO: Provide more information on package names and output version
      # TODO: Find: danieljurek, Replace: azure-sdk
      - pwsh: |
          $securePassword = ConvertTo-SecureString $env:GITHUB_PAT -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential('danieljurek', $securePassword)
          $body = '{ "title": "version increment ${{ parameters.PackageName }} $(OSVmImage)", "head": "danieljurek:${{ parameters.BranchName }}", "base": "$(Build.SourceBranchName)", "maintainer_can_modify": true }'
          Invoke-RestMethod -Method POST -Uri https://api.github.com/repos/${{ parameters.RepoName }}/pulls -Authentication Basic -Credential $cred -ContentType "application/json" -Body $body
        displayName: Open PR
        env:
          GITHUB_PAT: $(github-pat)
