resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools

jobs:
  - job: GO
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: eng/pipelines/templates/steps/cosmos-emulator.yml@azure-sdk-tools