resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      # Service Connection
      endpoint: Azure

jobs:
  - job: GO
    strategy:
      matrix:
        JavaParams:
          Url: 'https://acpedaily1.blob.core.windows.net/emulator/azure-cosmos-emulator.msi'
          StartParameters: -PartitionCount 100 -Consistency Strong
        JsParams:
          Url: 'https://aka.ms/cosmosdb-emulator'
        PythonParams:
          Url: 'https://acpedaily1.blob.core.windows.net/emulator/azure-cosmos-emulator.msi'



    pool:
      vmImage: vs2017-win2016
    steps:
      - template: eng/pipelines/templates/steps/cosmos-emulator.yml@azure-sdk-tools
        parameters:
          EmulatorMsiUrl: $(Url)
          StartParameters: $(StartParameters)