jobs:
  - job: "TestMuch"
    strategy:
      matrix:
        Ubuntu_1604:
          OSVmImage: ubuntu-16.04
        Ubuntu_1804:
          OSVmImage: ubuntu-18.04


    pool:
      vmImage: "$(OSVmImage)"

    steps:
    - script: ls -lah /usr/bin/
    - script: gcc-7 --version
      continueOnError: true
    - script: gcc-5 --version
      continueOnError: true
    - script: gcc-4 --version
      continueOnError: true

    - script: sudo apt update
    - script: sudo apt install -y g++-5 g++-4
    
    - script: gcc-7 --version
      continueOnError: true
    - script: gcc-5 --version
      continueOnError: true
    - script: gcc-4 --version
      continueOnError: true
