jobs:
  - job: "TestMuch"
    strategy:
      matrix:
        Ubuntu_1604:
          OSVmImage: ubuntu-16.04
        Ubuntu_1804:
          OSVmImage: ubuntu-18.04


    pool:
      vmImage: "$(OSVmImage)"

    steps:
    - script: ls -lah /usr/bin/
    - script: sudo apt update
    - script: sudo apt install -y g++-5 g++-4
    - script: g++-7 --version
    - script: g++-5 --version
    - script: g++-4 --version
