jobs:
  - job: "TestMuch"
    strategy:
      matrix:
        Windows:
          OSVmImage: vs2017-win2016
        Linux:
          OSVmImage: ubuntu-16.04
        OSX:
          OSVmImage: macOS-10.13
    steps:
    - script: |
        echo $RUN_IDENTIFIER
      displayName: "Show value"
      env:
        RUN_IDENTIFIER: $(Build.BuildId)$(Agent.JobName)