jobs:
  - job: "TestMuch"
    strategy:
      matrix:
        Windows2019:
          OSVmImage: windows-2019

    pool:
      vmImage: "$(OSVmImage)"

    steps:
    - pwsh: |
        ls  'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC'
      displayName: list stuff
